### ISSUE TITLE
Purchased upgrades have errant warnings

### ISSUE THREAD

**Issue by worldendDominator** [greenc/CookieMaster#36]
If you mouse over a purchased upgrade in Stats tab, the popup has Lucky, Lucky+Frenzy and Chain warnings without any numbers in them.

**Comment by greenc** [comment]
This should have been fixed a few versions ago. What version of CM are you running?

**Comment by worldendDominator** [comment]
Version 1.14.2. Wait, it disappeared now. Sorry for bothering.

**Comment by worldendDominator** [comment]
Actually, I revoke my previous comment.
Those warnings disappear when I save/load the game, but upgrades purchased in current session still have them.

**Comment by greenc** [comment]
Will look into this :)

**Comment by greenc** [comment]
Again, pretty sure this was fixed a while back but I forgot to update the issue. Please verify and reopen if the issue persists.
